AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  mineralDNA
  SAM application for mineralDNA

Globals:
  Function:
    Timeout: 3

    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  MineralDNAFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: mineral_dna/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Events:
        MineralDNA:
          Type: Api
          Properties:
            Path: /mineral_dna
            Method: POST
      Environment:
        Variables:
          POSTGRES_SECRET_ARN: "arn:aws:secretsmanager:eu-west-3:084828604969:secret:postgres_url-GmhUgh"

  RetrieveDNAFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: mineral_dna/
      Handler: retrieve_dna.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Events:
        RetrieveDNA:
          Type: Api
          Properties:
            Path: /retrieve_dna
            Method: GET
      Environment:
        Variables:
          POSTGRES_SECRET_ARN: "arn:aws:secretsmanager:eu-west-3:084828604969:secret:postgres_url-GmhUgh"
