AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  mineralDNA
  SAM application for mineralDNA

Globals:
  Function:
    Timeout: 3

    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  MineralDNAFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: mineral_dna/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Events:
        MineralDNA:
          Type: Api
          Properties:
            Path: /mineral_dna
            Method: POST
            Cors:
              AllowMethods: "OPTIONS,POST"
              AllowOrigins: "http://localhost:5173,https://mineral-dna.emilysteel.software"
              AllowHeaders: "*"
        MineralDNAOptions:
          Type: Api
          Properties:
            Path: /mineral_dna
            Method: OPTIONS
            Cors:
              AllowMethods: "OPTIONS,POST"
              AllowOrigins: "http://localhost:5173"
              AllowHeaders: "*"
